import Foundation

/// The two languages the interface speaks. Spanish is the default.
public enum UILanguage: String, CaseIterable, Sendable {
    case es, en

    /// How the language picker names it — in its own language, as macOS does.
    public var name: String {
        switch self {
        case .es: "Español"
        case .en: "English"
        }
    }
}

/**
 Every visible string, in Spanish and English.

 Keyed by the Spanish text, which is what the views show by default and what reads in
 the source: `tr("Asignar teclas")`. `table` gives the English. A string with values
 in it is a format — `tr("Conectado a %@", name)` — with the same placeholders in both
 languages (a test checks).

 Not localisation in the Foundation sense: no `.lproj`, no dependence on the system
 language. The app is Spanish unless the user picks English in the Device pane.

 ## Where the choice is stored — provisional, in one place

 `storedLanguage` is the only reader and writer of the choice. It uses UserDefaults
 under `defaultsKey` until the setting moves into `Preferences`; that move changes
 this getter and setter and nothing else.
 */
public enum UIStrings {
    public static let defaultLanguage: UILanguage = .es
    /// Provisional storage key. See `storedLanguage`.
    public static let defaultsKey = "uiLanguage"
    /// Posted after `storedLanguage` changes, for UI that is not SwiftUI (the menu bar).
    public static let didChange = Notification.Name("OpenBoardUILanguageDidChange")

    /// Forces a language regardless of the stored choice: tests and the snapshot
    /// harness, which must not write the user's defaults.
    nonisolated(unsafe) public static var override: UILanguage?

    /// The user's choice. PROVISIONAL: UserDefaults until it lives in `Preferences`.
    public static var storedLanguage: UILanguage {
        get {
            UserDefaults.standard.string(forKey: defaultsKey).flatMap(UILanguage.init(rawValue:))
                ?? defaultLanguage
        }
        set {
            UserDefaults.standard.set(newValue.rawValue, forKey: defaultsKey)
            NotificationCenter.default.post(name: didChange, object: nil)
        }
    }

    /// The language strings are resolved in right now.
    public static var current: UILanguage { override ?? storedLanguage }

    /// `spanish` in the current language. A key missing from the table falls back to
    /// the Spanish rather than to nothing; a test keeps the table complete.
    public static func text(_ spanish: String) -> String {
        switch current {
        case .es: spanish
        case .en: table[spanish] ?? spanish
        }
    }

    /// Spanish → English.
    public static let table: [String: String] = UIStringsTable.entries
}

/// A visible string in the current language, keyed by its Spanish text.
public func tr(_ spanish: String) -> String {
    UIStrings.text(spanish)
}

/// A visible format in the current language: `tr("Conectado a %@", name)`.
public func tr(_ spanish: String, _ arguments: CVarArg...) -> String {
    String(format: UIStrings.text(spanish), arguments: arguments)
}

/// The table itself, kept apart from the machinery above so the two read separately.
enum UIStringsTable {
    static let entries: [String: String] = [
        " y ": " and ",
        "%@ activó la entrada segura de teclado, que bloquea el HID de teclado para todas las apps. Tu permiso de Monitorización de entrada está bien: termina o cierra lo que la activó y el pad volverá.": "%@ has engaged Secure Keyboard Entry, which blocks keyboard HID for every app. Your Input Monitoring grant is fine — finish or quit whatever engaged it and the pad comes back.",
        "%@ esperan: pulsa una de esas teclas": "%@ are waiting — press one of those keys",
        "%@ está esperando": "%@ is waiting",
        "%@ está esperando en %@": "%@ is waiting on %@",
        "%@ no está en ejecución, así que no se puede preguntar a macOS si OpenBoard puede controlarlo. Se inicia cuando hace falta: usa una tecla que lo necesite y esto se resuelve solo.": "%@ is not running, so macOS cannot be asked whether OpenBoard may drive it. It starts on demand — use a key that needs it and this resolves itself.",
        "%@ se guarda, pero no se verá nada en el pad hasta que OpenBoard tenga lo que necesita. %@": "%@ is saved, but nothing will show on the pad until OpenBoard has what it needs. %@",
        "%@ · posición %ld": "%@ · slot %ld",
        "%@ — demasiado parecido al color de un estado; se omite": "%@ — too close to a state color, skipped",
        "%@. El pad vuelve a usar hooks.": "%@. The pad falls back to hooks.",
        "%ld bloqueada": "%ld blocked",
        "%ld bloqueadas": "%ld blocked",
        "%ld caracteres": "%ld characters",
        "%ld de %ld configurados": "%ld of %ld set up",
        "%ld de %ld hechos. Cada uno lleva unos segundos, y puedes parar y volver luego.": "%ld of %ld done. Each takes a few seconds, and you can stop and come back.",
        "%ld de %ld hooks necesita atención.": "%ld of %ld hooks needs attention.",
        "%ld de %ld hooks necesitan atención.": "%ld of %ld hooks need attention.",
        "%ld de %ld requiere atención.": "%ld of %ld needs attention.",
        "%ld de %ld requieren atención.": "%ld of %ld need attention.",
        "%ld líneas": "%ld lines",
        "%ld ms": "%ld ms",
        "%ld sesiones": "%ld sessions",
        "%ld sesiones encontradas. Las teclas siguen apagadas hasta que termines.": "%ld sessions found — the keys stay dark until this is finished.",
        "%ld sesión": "%ld session",
        "%ld sesión encontrada. Las teclas siguen apagadas hasta que termines.": "%ld session found — the keys stay dark until this is finished.",
        "AL GIRAR A LA DERECHA": "TURNING CLOCKWISE",
        "AL MANTENER": "HOLDING DOES",
        "AL MANTENER ESTA TECLA": "HOLDING THIS KEY",
        "AL PULSAR": "PRESSING DOES",
        "AL PULSAR ESTA TECLA": "PRESSING THIS KEY",
        "AL PULSARLA": "WHEN PRESSED",
        "AMARILLO": "YELLOW",
        "ATAJO QUE ENVÍA": "SHORTCUT IT SENDS",
        "AZUL": "BLUE",
        "Abrir": "Open",
        "Abrir OpenBoard al iniciar sesión": "Open OpenBoard at login",
        "Abrir al iniciar sesión": "Open at login",
        "Abrir configuración": "Open setup",
        "Accesibilidad": "Accessibility",
        "Aceptar": "OK",
        "Acerca de OpenBoard": "About OpenBoard",
        "Acorde": "Chord",
        "Agente nuevo y traspaso": "New agent and handoff",
        "Agrupar inicios en": "Group starts within",
        "Ajustes": "Settings",
        "Al día.": "Up to date.",
        "Al día. Última comprobación: %@.": "Up to date — last checked %@.",
        "Al girar a la izquierda hace siempre lo contrario.": "Counter-clockwise is always the opposite.",
        "Al mantenerla también hace algo": "Holding it does something too",
        "Al pulsar la tecla → %@": "Key press → %@",
        "Al recorrer espacios de trabajo solo se anima donde te detienes.": "Cycling through workspaces animates only where you stop.",
        "Apagada": "Not lit",
        "Apagado": "Off",
        "Apagado usa solo hooks y enlaces profundos, como antes.": "Off uses hooks and deep links only, as before.",
        "Apagado, salvo una vuelta cuando algo cambia.": "Dark, except for a lap when something changes.",
        "Apuntar con": "Aim with",
        "Archivos": "Files",
        "Armado": "Armed",
        "Asignaciones del pad": "Pad bindings",
        "Asignar teclas": "Map keys",
        "Asignar tus teclas": "Map your keys",
        "Aspecto": "Look",
        "Auto": "Auto",
        "Automatización": "Automation",
        "Automatización → %@": "Automation → %@",
        "Avanzado": "Advanced",
        "Azul": "Blue",
        "Añade OpenBoard a ~/.claude/settings.json para que las sesiones informen de lo que hacen. Se conservan los demás ajustes y antes se respalda el archivo.": "Adds OpenBoard to ~/.claude/settings.json so sessions report what they are doing. Every unrelated setting is preserved and the file is backed up first.",
        "Añadir": "Add",
        "Añadir un color": "Add a color",
        "Añadir un perfil para una app": "Add a profile for an app",
        "Aún no hay ninguno. Una tecla de agente envía el texto de arriba.": "None yet. An agent key sends the text above.",
        "Aún sin comprobar.": "Not checked yet.",
        "Aún sin respuesta de %@.": "No answer yet for %@.",
        "BRILLO": "BRIGHTNESS",
        "Baja": "Scrolls down",
        "Barrido en el anillo": "Sweep the ring",
        "Barrido y cuenta": "Sweep and count",
        "Batería aún sin leer: puede que el pad esté en reposo.": "Battery not read yet — the pad may be asleep.",
        "Batería del Codex Micro": "Codex Micro battery",
        "Blanca por defecto: el ámbar ya significa que una sesión te espera.": "White by default: amber already means a session waits on you.",
        "Bloqueada en una solicitud de permiso.": "Blocked on a permission prompt.",
        "Bloqueado: %@": "Blocked: %@",
        "Borrar": "Delete",
        "Brillo del anillo": "Ring brightness",
        "Busca más o menos una vuelta antes del fundido.": "Aim for about one lap before the fade.",
        "Buscando el pad": "Looking for the pad",
        "Buscando…": "Looking for Superset…",
        "Buscar actualizaciones automáticamente": "Check for updates automatically",
        "Buscar sesiones activas": "Find running sessions",
        "CIAN": "CYAN",
        "CONTEXTO": "CONTEXT",
        "Cada color debe elegirse exactamente una vez.": "Each color must be chosen exactly once.",
        "Cada guiño dura": "Each wink lasts",
        "Cada paso del fundido": "Each fade step",
        "Cada sesión conserva su tecla, esté en primer plano el espacio de trabajo que esté.": "Every session keeps its own key, whichever workspace is in front.",
        "Cada uno se aplica al reiniciar OpenBoard.": "Each takes effect after OpenBoard restarts.",
        "Cambia las teclas de golpe, sin un nuevo barrido.": "Changes the keys in one step, without a new sweep.",
        "Cambiar de nuevo en": "Switch again within",
        "Cambio de espacio de trabajo": "Switching workspaces",
        "Cancelar": "Cancel",
        "Carmesí": "Crimson",
        "Casi blanco — el pad reposa en blanco, así que parecerá apagado.": "Near-white — the pad rests white, so this reads as unlit.",
        "Cerrar": "Close",
        "Chat sin título": "Untitled chat",
        "Cian": "Cyan",
        "Clientes SDK integrados": "Embedded SDK clients",
        "Codex repinta estos LEDs a su ritmo: usa esto si se desajustan.": "Codex repaints these LEDs on its own schedule — use this if they drift.",
        "Color": "Color",
        "Color de la paleta": "Palette color",
        "Color propio": "Its own color",
        "Color y hex": "Color and hex",
        "Color, hex y velocidad": "Color, hex and speed",
        "Colores": "Colors",
        "Colores de espacios": "Workspace colors",
        "Como mucho un barrido cada": "At most one sweep every",
        "Como mucho una escritura al pad cada": "At most one pad write every",
        "Completo": "Full",
        "Comprobado el %@: el orden estándar, posición 1 arriba a la izquierda.": "Checked on %@ — the standard order, slot 1 top-left.",
        "Comprobado: el orden estándar, posición 1 arriba a la izquierda.": "Checked — the standard order, slot 1 top-left.",
        "Comprobando": "Checking",
        "Comprobando la interfaz HID.": "Checking the HID interface.",
        "Comprobando permisos…": "Checking permissions…",
        "Comprobar": "Check",
        "Comprobar ahora": "Check now",
        "Comprobar de nuevo": "Check again",
        "Comprobar orden de teclas": "Check key order",
        "Comprobar sesiones al abrir": "Check sessions at launch",
        "Comprueba el orden de teclas": "Check the key order",
        "Conceder": "Grant",
        "Conceder permisos": "Grant permissions",
        "Concedido: %@.": "Granted: %@.",
        "Conecta antes el pad.": "Connect the pad first.",
        "Conecta antes el pad: la comprobación pinta seis colores en él.": "Connect the pad first — the check paints six colours on it.",
        "Conecta el pad por USB o Bluetooth. Si ya está conectado, comprueba que esté en la capa 1.": "Connect the pad over USB or Bluetooth. If it is plugged in, check that it is on Layer 1.",
        "Conectado": "Connected",
        "Conectado a %@": "Connected to %@",
        "Conectado por USB. El nivel de batería se publica por Bluetooth, que el pad desactiva mientras está conectado al cable.": "Plugged in over USB. The battery level is published over Bluetooth, which the pad drops while it is on the cable.",
        "Conectado · %@": "Connected · Superset %@",
        "Conectado. Hay una copia de seguridad del archivo anterior a su lado.": "Wired. A backup of the previous file is beside it.",
        "Conexión": "Connection",
        "Configura OpenBoard": "Set up OpenBoard",
        "Configurar": "Set up",
        "Configurar OpenBoard": "Set up OpenBoard",
        "Configurar OpenBoard y mantenerlo en marcha.": "Setting OpenBoard up, and keeping it running.",
        "Confirma o cierra las restauradas de la última vez.": "Confirm or end the ones restored from last time.",
        "Confirma qué tecla física es la posición 1. El tablero asume el orden que reportan todos los pads, así que esto lleva diez segundos; pero los colores y las asignaciones van por posición, y un orden sin comprobar los pone en las teclas equivocadas.": "Confirms which physical key is slot 1. The board assumes the order every pad reports, so this takes ten seconds — but colours and bindings are set per slot, and an unchecked order puts them on the wrong keys.",
        "Confirmación": "Confirmation",
        "Confirmación en dos pasos": "Two-step confirmation",
        "Confirmar": "Confirm",
        "Contar duplicados una vez en": "Count duplicates once within",
        "Contexto que se pasa": "Context passed on",
        "Continuar configuración": "Continue setup",
        "Controlar System Events, que es lo que usan las teclas de acción. OpenBoard se lo pide directamente a macOS, sin pasar por Ajustes del Sistema.": "Driving System Events, which the key actions use. OpenBoard asks macOS directly — no trip to System Settings.",
        "Copiado.": "Copied.",
        "Copiar": "Copy",
        "Cortar": "Cut",
        "Corte": "Cut",
        "Cuándo borra el tablero un color por su cuenta.": "When the board clears a color on its own.",
        "Cuánto dura un color": "How long a color stays",
        "Cómo OpenBoard lee los agentes de Superset y actúa sobre ellos.": "How OpenBoard reads Superset's agents and acts on them.",
        "Cómo llega un toque de voz a Claude Code.": "How a voice tap reaches Claude Code.",
        "Cómo se detecta una sesión y qué hace su tecla.": "How a session is found, and what its key does.",
        "Cómo se llama este pad en todo OpenBoard.": "What this pad is called everywhere in OpenBoard.",
        "Cómo se muestra este harness": "How this harness is shown",
        "Cómo se ve cada uno en una tecla de sesión.": "What each one looks like on a session key.",
        "De la paleta": "From the palette",
        "Deja de seguir esta sesión y libera su tecla. La sesión sigue en marcha.": "Stop tracking this session and free its key. The session keeps running.",
        "Denegado: %@. Actívalo en Ajustes del Sistema → Privacidad y seguridad → Automatización.": "Refused: %@ — turn these on in System Settings → Privacy & Security → Automation.",
        "Desactivado deja la cuenta solo en las teclas.": "Off keeps the count-up on the keys only.",
        "Deshacer": "Undo",
        "Desplaza la ventana que está bajo el puntero.": "Scrolls the window under the pointer.",
        "Después envíale algo — el resto se completa a partir de ahí.": "Then send it something — the rest fills in from there.",
        "Después se cancela solo.": "Then it cancels on its own.",
        "Detectada automáticamente": "Detected automatically",
        "Detectar": "Detect",
        "Detener": "Stop",
        "Dispositivo": "Device",
        "Diversión": "Fun",
        "Dónde funciona": "Where it works",
        "Dónde se guardan tus ajustes y el registro.": "Where your settings and log are kept.",
        "EFECTO": "EFFECT",
        "ESPACIOS DE TRABAJO": "WORKSPACES",
        "ESTADO": "STATUS",
        "ESTADO — CLIC EN LA MUESTRA: COLOR, HEX Y VELOCIDAD": "STATE — CLICK THE SWATCH FOR COLOR, HEX & SPEED",
        "Edición": "Edit",
        "El Bluetooth está desactivado": "Bluetooth is off",
        "El Bluetooth está desactivado, así que el pad no puede conectarse.": "Bluetooth is switched off, so the pad cannot connect at all.",
        "El Codex Micro está enlazado pero no conectado. Pulsa cualquier tecla del pad para despertarlo; hasta entonces, cada color que ves aquí es lo último que pidió OpenBoard, no lo que muestra el pad.": "The Codex Micro is paired but not connected. Press any key on the pad to wake it — until then every color here is the last thing OpenBoard asked for, not what the pad is showing.",
        "El anillo": "The ring",
        "El anillo hace un barrido con el color del espacio de trabajo mientras las teclas se encienden una a una.": "The ring sweeps once in the workspace's color while the keys light one by one.",
        "El anillo se mantiene antes del fundido": "Ring holds before fading",
        "El anillo sigue apagado durante los primeros %.1fs.": "The ring stays dark for the first %.1fs.",
        "El aspecto de las teclas": "How the keys look",
        "El final de la pantalla de la sesión activa.": "The end of the focused session's screen.",
        "El mismo evento desde un hook y desde Superset.": "The same event from a hook and from Superset.",
        "El pad está aquí y OpenBoard tiene permiso para leerlo, pero otra app lo tiene abierto. Lo habitual es que siga abierta una copia antigua de OpenBoard.": "The pad is here and OpenBoard is allowed to read it, but something else has it open. An older copy of OpenBoard still running is the usual cause.",
        "El pad está en vivo y tus sesiones le informarán. Siguiente: elige qué hace cada tecla y cómo se ve; esa parte es toda tuya.": "The pad is live and your sessions will report to it. Next: choose what each key does and how it looks — that part is entirely yours.",
        "El pad solo sigue hooks y enlaces profundos. Cambia a Auto para usar Superset directamente.": "The pad follows hooks and deep links only. Switch to Auto to use Superset directly.",
        "El proceso propietario, y el tty de la sesión tomado de él al asignarle la tecla.": "The owning process, and the session's tty captured from it at claim time.",
        "El proceso propietario. Después cmux indica la superficie en la que corre el pid de la sesión.": "The owning process. cmux then names the surface the session's pid is running in.",
        "El proceso propietario. Un tty por sí solo no distingue iTerm2 de Terminal — ambos asignan uno real.": "The owning process. A tty alone cannot tell iTerm2 from Terminal — both allocate a real one.",
        "El texto más largo se corta en el límite de un carácter.": "Longer text is cut at a character boundary.",
        "El traspaso pasa la sesión activa a": "Handoff passes the focused session to",
        "El tty del proceso propietario, si la sesión se inició desde uno.": "The owning process's tty, when the session was started from one.",
        "El turno falló.": "The turn failed.",
        "Elige el color que ves en cada tecla: primero la fila de arriba, de izquierda a derecha.": "Pick the color you can see on each key — top row first, left to right.",
        "Empareja el Codex Micro con este Mac por Bluetooth o USB y mantenlo en la capa 1: el estado por tecla solo se muestra ahí.": "Pair the Codex Micro with this Mac over Bluetooth or USB, and keep it on Layer 1 — per-key status renders only there.",
        "Empuja el joystick a la derecha": "Push the stick right",
        "Empuja el joystick a la izquierda": "Push the stick left",
        "Empuja el joystick hacia abajo": "Push the stick down",
        "Empuja el joystick hacia arriba": "Push the stick up",
        "En el espacio de trabajo en primer plano. Fuera de uno no pasa nada.": "In the workspace in front. Nothing happens outside one.",
        "En el propio pad": "On the pad itself",
        "Entrar en pantalla completa": "Enter Full Screen",
        "Entre medias, las teclas siguen encendiéndose en cuenta.": "The keys still count up in between.",
        "Entre teclas": "Between keys",
        "Envía": "Sends",
        "Envío máximo": "Longest send",
        "Envíos remotos": "Remote sends",
        "Escribir textos, enviar ⏎ y ⎋ y desplazarse con el dial.": "Typing snippets, sending ⏎ and ⎋, and scrolling with the dial.",
        "Escritura": "Typing",
        "Espacio escribe un espacio si la entrada ya tiene texto. ⌃Y inicia el dictado y no escribe nada: OpenBoard añade por ti la línea del atajo a ~/.claude/keybindings.json.": "Space types a space when the input already has text. ⌃Y starts dictation and types nothing — OpenBoard adds the one-line binding to ~/.claude/keybindings.json for you.",
        "Espacios de trabajo": "Workspaces",
        "Espera": "Waits for",
        "Esperando a que arranque el host-service de Superset.": "Waiting for Superset's host-service to start.",
        "Esperando aprobación en Ajustes del Sistema → General → Ítems de inicio.": "Waiting for approval in System Settings → General → Login Items.",
        "Esperar a que el cambio se asiente": "Wait for the switch to settle",
        "Estados": "States",
        "Este sensor no ha enviado nunca ningún evento.": "No event has ever been observed from this sensor.",
        "Está en este Mac, pero nunca ha informado al tablero.": "Found on this Mac, and it has never reported to the board.",
        "Eventos": "Events",
        "Eventos en vivo": "Live events",
        "Evita que una ráfaga de eventos sature el pad.": "Keeps a burst of events from flooding the pad.",
        "Falta: %@.": "Still needed: %@.",
        "Faltan: %@": "Missing: %@",
        "Faltan: %@.": "Still needed: %@.",
        "Fija por defecto: todas las teclas locales respiran, así que fija se lee como «no es de aquí».": "Still by default: every local key breathes, so still reads as “not from here”.",
        "Girar mientras dictas": "Spin while dictating",
        "Grabación de pantalla": "Screen Recording",
        "Grabar atajo": "Record shortcut",
        "Guardado en %@": "Saved to %@",
        "Guardar": "Save",
        "Guiño cada": "Wink every",
        "Guiño con el color del espacio de origen": "Wink the origin workspace's color",
        "Hay un turno (o un subagente delegado) en marcha.": "A turn — or a delegated subagent — is running.",
        "Haz clic en una tecla para ver qué hace y cambiar su tapa.": "Click a key to see what it does and change its cap.",
        "Heredado de Todas las apps.": "Inherited from All apps.",
        "Heredar de nuevo": "Inherit again",
        "Hooks de Claude Code": "Claude Code hooks",
        "Hooks instalados. Abre una sesión nueva de Claude Code para verlo: se cargan al iniciar la sesión, así que las que ya están en marcha no se iluminarán.": "Hooks wired. Open a new Claude Code session to see it — they load when a session starts, so ones already running will not light.",
        "Host-service": "Host-service",
        "Idioma": "Language",
        "Ignorar un segundo NEW en": "Ignore a second NEW within",
        "Igual en todas las apps. Cámbialo en Todas las apps.": "Same in every app. Change it under All apps.",
        "Ilumina las teclas en cuanto un agente empieza o se detiene.": "Light keys the moment an agent starts or stops.",
        "Inactiva, y es el chat que estás mirando.": "Idle, and the chat you are looking at.",
        "Inalcanzable: los hooks corren en el propio proceso de la sesión, y solo uno local puede hablar con el pad.": "Unreachable: hooks run in the session's own process, and only a local one can talk to the pad.",
        "Inicio": "Starting up",
        "Instalados. Abre una sesión nueva de Claude Code para verlo: los hooks se cargan al iniciar la sesión, así que las que ya están en marcha no se iluminarán. El archivo de ajustes anterior queda respaldado a su lado.": "Wired. Open a new Claude Code session to see it — hooks load when a session starts, so ones already running will not light. The previous settings file is backed up beside it.",
        "Instalar": "Install",
        "La entrada segura de teclado bloquea el pad": "Secure Keyboard Entry is blocking the pad",
        "La luz exterior, que resume todo el tablero.": "The outer light, which summarises the whole board.",
        "La luz que pregunta antes de hacer un traspaso.": "The light that asks before a handoff goes through.",
        "La superficie, por id, a través del socket de cmux — la pestaña o división exacta, cambiando de espacio de trabajo si está en otro. No hace falta el permiso de Automatización.": "The surface, by id, over cmux's own socket — the exact tab or split, switching workspace if it is in another one. No Automation grant needed.",
        "La tecla 6, prestada a una sesión urgente de otro espacio de trabajo.": "Key 6, lent to an urgent session from another workspace.",
        "La tecla de voz": "The voice key",
        "La versión %@ está disponible.": "Version %@ is available.",
        "Las actualizaciones están desactivadas en esta compilación del fork: recompílala para actualizar.": "Updates are off in this fork build — rebuild it to update.",
        "Las teclas cambian de golpe. Nada en el anillo.": "The keys change in one step. Nothing on the ring.",
        "Las teclas de agente siempre saltan a su posición y no se pueden reasignar.": "Agent keys always jump to their slot and cannot be rebound.",
        "Las teclas muestran agentes, pero NEW, el traspaso y los envíos remotos están desactivados hasta comprobar esta versión.": "Keys show agents, but NEW, the handoff and remote sends are off until this version is checked.",
        "Las teclas muestran las sesiones del espacio de trabajo en primer plano; lo urgente de otros toma prestada la tecla 6.": "Keys show the sessions of the workspace in front; anything urgent elsewhere borrows key 6.",
        "Las teclas siguen a los agentes de Superset y todas las acciones de Superset están disponibles.": "Keys follow Superset's agents, and every Superset action is available.",
        "Leer el pad. Sin él no se ilumina nada y no se detecta ninguna pulsación.": "Reading the pad. Without it nothing lights and no key press is seen.",
        "Leyendo el manifiesto de Superset y comprobando su versión.": "Reading Superset's manifest and checking its version.",
        "Libre": "Free",
        "Listo": "Done",
        "Lo mantiene mientras pulsas": "Holds it while pressed",
        "Lo que hace cada tecla": "What each key does",
        "Lo que recibe una tecla de agente si no se elige otra cosa.": "What an agent key receives when nothing else is chosen.",
        "Lo rápido que se encienden las teclas en cuenta.": "How fast the keys count up.",
        "Lo toca": "Taps it",
        "Los %ld eventos conectados a esta compilación.": "All %ld wired to this build.",
        "Los LED del anillo": "The ring's LEDs",
        "Los LED del anillo, en su ajuste de un color": "The ring's LEDs, in its One color setting",
        "Los colores marcados se parecen demasiado a un estado y se omiten.": "Marked colors are too close to a state and are skipped.",
        "Luz": "Light",
        "LÍNEAS POR CLIC": "LINES PER CLICK",
        "Líneas que se revisan antes de enviar o interrumpir.": "Lines checked before a send or an interrupt.",
        "MAGENTA": "MAGENTA",
        "MODO DIVERSIÓN: reproduce el video y las luces lo siguen": "FUN MODE — play the video, lights follow",
        "Magenta": "Magenta",
        "Mantener": "Hold",
        "Mantener deja el atajo pulsado hasta que sueltas, como mantener para dictar.": "Hold keeps the chord down until you let go, like hold to dictate.",
        "Mantener encendidas las sesiones mientras te esperan": "Keep sessions lit while they wait for you",
        "Mantener encendidas las sesiones terminadas hasta que vuelvas": "Keep finished sessions lit until you go back",
        "Mantiene el color de la sesión más urgente. Las vueltas siguen saliendo.": "Holds the color of the most urgent session. Laps still fire.",
        "Mantiene un color haga lo que haga el tablero. Las vueltas siguen saliendo.": "Holds one color whatever the board is doing. Laps still fire.",
        "Mantén FAST para armar, pulsa REJ para convertirlo en interrupción y luego la tecla del agente.": "Hold FAST to arm, press REJ to make it an interrupt, then the agent's key.",
        "Mantén FAST para preparar el envío, pulsa REJ si prefieres interrumpir y luego pulsa esta tecla. Envía sin saltar a ella.": "Hold FAST to arm, press REJ if you want an interrupt instead, then press this key. It sends without jumping.",
        "Mantén esta tecla y pulsa FAST para enviar o REJ para interrumpir. Así, todos los saltos ocurren al soltar.": "Hold this key and press FAST to send, or REJ to interrupt. Every jump then happens on release.",
        "Mantén la tecla del agente y pulsa FAST para enviar o REJ para interrumpir.": "Hold the agent's key and press FAST to send, or REJ to interrupt.",
        "Mientras Superset está en primer plano.": "While Superset is in front.",
        "Minimizar": "Minimize",
        "Modo de Claude": "Claude's mode",
        "Modo diversión": "Fun mode",
        "Modos integrado y RPC": "Embedded and RPC modes",
        "Monitorización de entrada": "Input Monitoring",
        "Mostrar": "Reveal",
        "Mostrar este estado en el pad": "Show this state on the pad",
        "Mostrar sesiones de todos modos": "Show sessions anyway",
        "Mueve antes OpenBoard a /Applications: un ítem de inicio registrado desde otro sitio falla cuando esa carpeta cambia.": "Move OpenBoard to /Applications first — a login item registered from anywhere else breaks when that folder changes.",
        "Más tarde": "Later",
        "NEW inicia": "NEW starts",
        "Nada que conceder: todo lo que OpenBoard necesita ya está permitido.": "Nothing to grant — everything OpenBoard needs is already allowed.",
        "Naranja": "Orange",
        "Navegación": "Navigation",
        "Necesita Automatización → QuickTime Player, en el panel Dispositivo.": "Needs Automation → QuickTime Player, on the Device pane.",
        "Negro": "Off-black",
        "No hay ninguna otra app abierta": "No other app is running",
        "No hay ningún pad conectado": "No pad attached",
        "No hay un evento de aprobación documentado, así que una tecla de Pi nunca se pone naranja — justo el estado para el que existe este tablero.": "No approval event is documented, so a Pi key never turns orange — the one state this board exists for.",
        "No hay video instalado — pon uno en %@.": "No video installed — put one in %@.",
        "No hubo respuesta. Pulsa Conceder otra vez y acepta en el diálogo que muestra macOS.": "No answer was given. Press Grant again and choose OK in the dialog macOS shows.",
        "No se encontró el archivo de ajustes.": "No settings file found.",
        "No se encontró en este Mac.": "Not found on this Mac.",
        "No se encontró ningún %@": "No %@ found",
        "No se encontró ~/.claude/settings.json.": "No ~/.claude/settings.json found.",
        "No se han encontrado espacios de trabajo de Superset en este Mac.": "No Superset workspaces found on this Mac.",
        "No se pudo comprobar: %@": "Could not check: %@",
        "Nombre": "Name",
        "Notificaciones": "Notifications",
        "Nunca reciben tecla, a propósito: un solo reparto en paralelo ocuparía las seis a la vez.": "Never given a key, by design: one parallel fan-out would take all six at once.",
        "Nunca se enciende, ni siquiera con vueltas.": "Never lights, laps included.",
        "Ocultar OpenBoard": "Hide OpenBoard",
        "Ocultar otros": "Hide Others",
        "Ocupa todo el pad, estado incluido, mientras dura la canción.": "Takes over the whole pad, status included, for the song.",
        "Omitir por ahora": "Skip for now",
        "OpenBoard está configurado": "OpenBoard is set up",
        "OpenBoard está listo": "OpenBoard is ready",
        "OpenBoard necesita %@. Se conceden por app y solo surten efecto después de reiniciarla.": "OpenBoard needs %@. These are granted per app, and only take effect after the app is restarted.",
        "Orden de teclas": "Key order",
        "Orden personalizado registrado el %@: %@.": "Custom order recorded on %@: %@.",
        "Orden personalizado registrado: %@.": "Custom order recorded: %@.",
        "Organización": "Organization",
        "Otra app está usando el pad": "Something else is holding the pad",
        "Otra versión de Superset": "Another Superset version",
        "Otras herramientas lanzan `claude` por su cuenta — se vieron diez corriendo bajo una sola extensión ajena.": "Other tools spawn `claude` of their own accord — ten were seen running under one unrelated extension.",
        "Otro color…": "Other color…",
        "PALETA — UN ESPACIO DE TRABAJO SIN COLOR PROPIO TOMA UNO DE ESTOS": "PALETTE — A WORKSPACE WITHOUT ITS OWN COLOR TAKES ONE OF THESE",
        "Pad no disponible": "Pad unavailable",
        "Pad virtual": "Virtual Pad",
        "Pantalla leída antes": "Screen read first",
        "Pasos del fundido": "Fade steps",
        "Pegar": "Paste",
        "Permisos": "Permissions",
        "Permitido: %@": "Allowed: %@",
        "Permitir": "Allow",
        "Permitir comandos peligrosos": "Allow dangerous commands",
        "Pi se integra en otras apps. Esas sesiones no son algo que una tecla pueda traer al frente.": "Pi embeds in other apps. Those sessions are not something a key can raise.",
        "Pide a macOS permiso para controlar System Events y las terminales a las que salta una tecla: Terminal, e iTerm2 si está instalado. QuickTime no se incluye: el modo diversión lo pide por su cuenta la primera vez que lo reproduces.": "Asks macOS for permission to drive System Events and the terminals press-to-jump raises — Terminal, and iTerm2 when installed. QuickTime is not included — fun mode asks for that itself the first time you play it.",
        "Pizarra": "Slate",
        "Pregunta antes, con la luz de abajo.": "Asks first, with the light below.",
        "Preguntando": "Asking",
        "Preset…": "Preset…",
        "Prestar la tecla 6": "Lend key 6",
        "Previsualización del valor hex": "Preview of the hex value",
        "Primera tecla tras": "First key after",
        "Probado con %@. Solo lectura permite consultas, nunca escribir.": "Tested with %@. Read-only allows queries, never input.",
        "Probar el barrido": "Try the sweep",
        "Probar en el pad": "Try on the pad",
        "Pulsa la tecla otra vez dentro de este tiempo para confirmar; cualquier otra cosa cancela.": "Press the key again inside this to confirm; anything else cancels.",
        "Pulsa las teclas en tu teclado. Esc cancela.": "Press the keys on your keyboard. Esc cancels.",
        "Pulsa las teclas…": "Press keys…",
        "Punto de entrada `claude-vscode`, o el proceso propietario cuando la sesión corre en la terminal integrada.": "Entry point `claude-vscode`, or the owning process when a session runs in the integrated terminal.",
        "Quitar %@": "Remove %@",
        "Quitar de la paleta": "Remove from palette",
        "Quitar perfil": "Remove profile",
        "Qué compilación es y cómo se actualiza.": "Which build this is, and how it gets a newer one.",
        "Qué estado corresponde a cada subtipo de notificación.": "Which notification subtype means which state.",
        "Qué informa una sesión y si llega al tablero.": "What a session reports, and whether it reaches the board.",
        "Qué inician NEW y el traspaso en el espacio de trabajo activo.": "What NEW and the handoff start in the focused workspace.",
        "Qué sesiones muestran las teclas": "Which sessions the keys show",
        "Qué sesión de Superset sigue el pad.": "Which Superset login the pad follows.",
        "REMOTO": "REMOTE",
        "REPRODUCIR UNO AHORA": "PLAY ONE NOW",
        "ROJO": "RED",
        "Reasignar": "Remap",
        "Recalibrar": "Recalibrate",
        "Reconectar": "Reconnect",
        "Registro": "Log",
        "Rehacer": "Redo",
        "Reiniciar OpenBoard": "Restart OpenBoard",
        "Reinstalar": "Re-wire",
        "Reintentar": "Retry",
        "Reparar": "Repair",
        "Reparar hooks": "Repair hooks",
        "Repetir ×%ld": "Repeat ×%ld",
        "Repintar": "Repaint",
        "Reproduce la luz en el pad con una prueba inofensiva armada: APPR confirma, cualquier otra tecla cancela. En ningún caso se ejecuta nada.": "Plays the light on the pad with a harmless test armed: APPR confirms, any other key cancels. Nothing runs either way.",
        "Reproducir": "Play",
        "Reproducir %@": "Play %@",
        "Respetar Reducir movimiento": "Follow Reduce Motion",
        "Restablecer valores predeterminados": "Reset to defaults",
        "Restaurada al abrir la app, aún no vista en vivo.": "Restored at launch, not yet seen live.",
        "SE MANTIENE TRAS": "HELD AFTER",
        "SENSOR TÁCTIL": "TOUCH SENSOR",
        "Salir de OpenBoard": "Quit OpenBoard",
        "Saltó un aviso de inactividad.": "An idle prompt fired.",
        "Se aplica a todas las teclas de texto. Una tecla que escribe /clear en la ventana equivocada no se puede deshacer.": "Applies to every snippet key. A key that types /clear into the wrong window cannot be undone.",
        "Se aplica al reiniciar OpenBoard.": "Takes effect after OpenBoard restarts.",
        "Se aplica el límite propio de Superset hasta comprobarlo.": "Superset's own limit applies until it has been checked.",
        "Se borra al responder, o a los 15 min si nadie responde.": "Clears when answered, or after 15 minutes if it never is.",
        "Se borra cuando le envías algo a esa sesión.": "Clears when you send that session something.",
        "Se borra en cuanto respondes.": "Clears the moment the prompt is answered.",
        "Se borra tras": "Clears after",
        "Se compara con el tty de cada pestaña de Terminal — la pestaña exacta, no la ventana.": "Matched against Terminal's per-tab tty — the exact tab, not the window.",
        "Se compara con el tty de cada sesión de iTerm2, un nivel más fino que Terminal: la división exacta, no solo la pestaña.": "Matched against iTerm2's per-session tty, one level deeper than Terminal: the exact split, not just the tab.",
        "Se escribe en el cursor. No se envía.": "Typed at the cursor. Not submitted.",
        "Se puede editar a mano. Guarda algunos ajustes que esta ventana no muestra.": "Safe to hand-edit. Holds a few settings this window does not show.",
        "Seguir la organización que tenga manifiesto": "Follow whichever org has a manifest",
        "Seis teclas, en vivo.": "Six keys, live.",
        "Seleccionar todo": "Select All",
        "Sesiones de gateway": "Gateway sessions",
        "Sesión abierta, sin nada en marcha.": "Session open, nothing running.",
        "Sesión cerrada.": "Session closed.",
        "Si está activado en macOS, un cambio pasa las teclas de golpe.": "With it on in macOS, a switch changes the keys in one step.",
        "Si la tecla de voz del pad coincide con el modo de Claude.": "Whether the pad's voice key matches Claude's mode.",
        "Siempre activado": "Always on",
        "Sigue armado durante": "Stays armed for",
        "Simulado: los mismos bytes que el hardware. Mantén una tecla para mantenerla de verdad.": "Simulated — the same bytes as hardware. Hold a key for a real hold.",
        "Sin comprobar. Se usa el orden que reportan todos los pads hasta ahora: posición 1 arriba a la izquierda y luego en orden de lectura.": "Not checked. Running on the order every pad so far reports — slot 1 top-left, then reading order.",
        "Sin conectar, y aunque lo estuvieran no recibirían tecla — seis teclas son un recurso escaso.": "Not wired, and would not take a key if it were — six keys is a scarce budget.",
        "Sin conexión": "Not connected",
        "Sin conexión por Bluetooth": "Not connected over Bluetooth",
        "Sin escuchar — las sesiones de aquí no reciben tecla.": "Not listening — sessions here get no key.",
        "Sin evento de finalización: nada en sus hooks de shell significa \"este turno terminó\", así que una tecla de Hermes nunca se pone verde.": "No completion event: nothing in its shell hooks means \"this turn ended\", so a Hermes key never turns green.",
        "Sin luz": "Never light",
        "Sin verificar aún": "Not verified yet",
        "Sobrescribir": "Override",
        "Sobrescrita en esta app": "Overridden in this app",
        "Solo a un agente detenido": "Only to an agent that has stopped",
        "Solo a un agente que se haya detenido.": "Only to an agent that has stopped.",
        "Solo admite extensiones dentro del proceso, así que la configuración es un archivo que añades tú, no un comando que OpenBoard pueda instalar.": "In-process extensions only, so setup is a file you add rather than a command OpenBoard can install.",
        "Solo el espacio activo": "Only the focused workspace",
        "Solo lectura": "Read-only",
        "Solo lectura · %@": "Read-only · Superset %@",
        "Solo lectura: versión %@ ≠ probada %@": "Read-only: version %@ ≠ tested %@",
        "Solo se ven de pasada: el barrido y el guiño de la tecla prestada.": "Seen only in passing: the sweep, and the borrowed key's wink.",
        "Solo si el espacio de trabajo en primer plano tiene cinco sesiones o menos.": "Only when the workspace in front has five sessions or fewer.",
        "Solo vueltas": "Laps only",
        "Subagentes": "Subagents",
        "Sube": "Scrolls up",
        "Superset": "Superset",
        "Superset ya no lo muestra": "Not listed by Superset any more",
        "System Events no se inició, así que macOS no tenía nada que preguntar. Vuelve a intentarlo en un momento.": "System Events would not start, so macOS had nothing to ask about. Try again in a moment.",
        "TAPA": "KEYCAP",
        "TEXTO QUE ESCRIBE": "TEXT IT TYPES",
        "TEXTOS CON NOMBRE": "NAMED SNIPPETS",
        "Tablero": "Board",
        "Tecla prestada": "Borrowed key",
        "Tecla prestada tras las demás": "Borrowed key after the others",
        "Teclas de acción": "Action keys",
        "Teclas de agente": "Agent keys",
        "Termina la configuración primero": "Finish setting up first",
        "Termina un chat": "A chat finishes",
        "Terminó y aún no has vuelto a ella.": "Finished, and you have not been back yet.",
        "Texto que se escribe en un agente sin cambiar a él.": "Text typed into an agent without switching to it.",
        "Tiempos": "Timing",
        "Tocar": "Tap",
        "Tocar ⌃Y en vez de espacio": "Tap ⌃Y instead of space",
        "Todas las apps": "All apps",
        "Todas las sesiones": "Every session",
        "Todas las teclas a la vez, con el anillo fijo un instante en el color del espacio de trabajo.": "Every key at once, with a brief solid ring in the workspace's color.",
        "Todo lo que necesita está concedido. Abre una sesión nueva de Claude Code y las teclas se iluminarán.": "Everything it needs is granted. Open a new Claude Code session and the keys will light.",
        "Todos los permisos concedidos": "All permissions granted",
        "Tu pad debería verse así.": "Your pad should look like this.",
        "UUID del preset": "preset UUID",
        "Un agente informa de un inicio en cada uso de herramienta.": "An agent reports a start on every tool use.",
        "Un color": "One color",
        "Un destello breve que indica dónde está la sesión.": "A brief flash that says where the session lives.",
        "Un empuje es una acción, por mucho que lo mantengas.": "One push is one action, however long you hold it.",
        "Un tablero que tienes que acordarte de abrir no es un tablero ambiental.": "A board you have to remember to launch is not an ambient board.",
        "Una doble pulsación inicia un agente, no dos.": "A double press starts one agent, not two.",
        "Una ejecución de gateway no es una terminal a la que se te pueda llevar, y puede que ni siquiera esté en este Mac.": "A gateway run is not a terminal you can be sent to, and may not be on this machine at all.",
        "Una luz breve al cambiar de espacio de trabajo y luego el pad como siempre.": "A short light when you change workspace, then the pad as usual.",
        "Una regla de seguridad, no una preferencia: nunca se escribe en un agente ocupado.": "A safety rule, not a preference: a busy agent is never typed into.",
        "Una tapa, dos interruptores: se asigna como %@.": "One keycap, two switches — bound as %@.",
        "Una tecla con acción al mantener espera este tiempo antes de tocar; una sin ella toca al instante.": "A key with a hold waits this long before tapping; one without taps at once.",
        "Uno falla": "One fails",
        "Uno te necesita": "One needs you",
        "Usar la paleta": "Use the palette",
        "VERDE": "GREEN",
        "VUELTAS": "LAPS",
        "Velocidad": "Speed",
        "Velocidad del anillo": "Ring speed",
        "Ventana": "Window",
        "Ver tablero": "Show the board",
        "Verde": "Green",
        "Versión": "Version",
        "Versión %@ disponible": "Version %@ is available",
        "Violeta": "Violet",
        "Visualización": "View",
        "Volver a comprobar": "Re-check",
        "Voz": "Voice",
        "Ya casi está.": "Almost there.",
        "Zoom": "Zoom",
        "`CLAUDE_AGENT_ID`, o un tipo de agente en el payload.": "`CLAUDE_AGENT_ID`, or an agent type in the payload.",
        "`code -r` sobre la carpeta del proyecto: la ventana correcta, no el panel concreto.": "`code -r` on the workspace folder: the right window, not the specific panel.",
        "`cwd` y `session_id` del payload del hook.": "`cwd` and `session_id` from the hook payload.",
        "`session_id` y `cwd`, reenviados por la extensión.": "`session_id` and `cwd`, forwarded by the extension.",
        "`subagent_start` y `subagent_stop`.": "`subagent_start` and `subagent_stop`.",
        "a la vista": "viewing",
        "abrir Ajustes": "open settings",
        "abrir al iniciar sesión": "Open at login",
        "abrir el menú": "open the menu",
        "abrir el menú de la barra de menús": "open the menu bar dropdown",
        "acorde": "chord",
        "activar o desactivar la voz": "toggle voice",
        "agente nuevo": "new agent",
        "agente nuevo en el espacio de trabajo activo de Superset": "new agent in the focused Superset workspace",
        "antirrebote": "debounced",
        "apagado": "off",
        "apagar todas las teclas": "all keys off",
        "aprobar": "approve",
        "aprobar la solicitud pendiente (⏎)": "approve pending prompt (⏎)",
        "apunta a otra instalación — %@": "points at another install — %@",
        "apunta a otra instalación: %@": "points at another install — %@",
        "apunta a un binario que ya no existe — %@": "points at a binary that is gone — %@",
        "apunta a un binario que ya no existe: %@": "points at a binary that is gone — %@",
        "arcoíris": "rainbow",
        "armado": "armed",
        "atajo de teclado personalizado (se graba abajo)": "custom keyboard shortcut (recorded below)",
        "atajo personalizado": "custom shortcut",
        "bytes": "bytes",
        "cerrada": "ended",
        "claude.ai, nube, SSH": "claude.ai, cloud, SSH",
        "cmux": "cmux",
        "concedido": "granted",
        "confirmación en dos pasos": "two-step confirm",
        "controlar %@": "driving %@",
        "cuando haga falta": "when needed",
        "degradado": "gradient",
        "denegado": "denied",
        "depende del subtipo": "depends on the subtype",
        "detenida": "stalled",
        "dial · girar y pulsar": "dial · turn and click",
        "el que más espera": "oldest waiting",
        "elegir": "pick",
        "enviar ⏎": "send ⏎",
        "enviar ⏎ a la ventana activa": "send ⏎ to the focused window",
        "envío remoto": "remote send",
        "error": "error",
        "escribir texto": "type snippet",
        "escribir texto en el cursor": "type snippet at cursor",
        "escribir textos, enviar ⏎ y ⎋, desplazarse": "typing snippets, sending ⏎ and ⎋, scrolling",
        "escribir textos, ⏎ y ⎋, flechas": "typing snippets, ⏎ and ⎋, arrow keys",
        "esperando": "awaiting",
        "fijo": "solid",
        "flecha abajo": "arrow down",
        "flecha arriba": "arrow up",
        "flecha derecha": "arrow right",
        "flecha izquierda": "arrow left",
        "fuera del pad": "off the pad",
        "hooks de Claude Code": "Claude Code hooks",
        "inactiva": "idle",
        "inactivo": "not running",
        "interrumpir agente": "interrupt agent",
        "interrumpir el agente activo (⎋ vía Superset)": "interrupt the focused agent (⎋ via Superset)",
        "ir a la sesión que más lleva esperando": "jump to the session waiting longest",
        "joystick · un empuje, una acción": "stick · one push, one action",
        "lee la pantalla antes": "reads the screen first",
        "leer el nivel de batería del pad": "reading the pad's battery level",
        "leer el pad: toda la iluminación y cada tecla": "reading the pad — all lighting and every key",
        "macOS denegó el acceso": "macOS denied access",
        "macOS tiene registrada una negativa para System Events, así que no volverá a preguntar. Activa OpenBoard en Automatización, en Ajustes del Sistema, y luego vuelve y pulsa Comprobar de nuevo.": "macOS has a refusal on record for System Events, so it will not ask again. Turn OpenBoard on under Automation in System Settings, then come back and press Check again.",
        "mantener para dictar": "hold to dictate",
        "mantener para dictar (requiere voice.mode=hold)": "hold to dictate (needs voice.mode=hold)",
        "modo diversión": "fun mode",
        "nada": "nothing",
        "ninguna tecla asignada a una acción de voz": "no key bound to a voice action",
        "nombre": "name",
        "nueva pestaña de Terminal": "new Terminal tab",
        "nueva pestaña de cmux": "new cmux tab",
        "nueva pestaña de cmux (en el espacio de trabajo actual)": "new cmux tab (in the workspace you are in)",
        "nuevo espacio de trabajo de cmux": "new cmux workspace",
        "nuevo espacio de trabajo de cmux (el ⌘N de cmux)": "new cmux workspace (cmux's own ⌘N)",
        "ok": "ok",
        "olvidar sesiones": "forget sessions",
        "opcional": "optional",
        "orden de teclas": "Key order",
        "pestaña anterior": "previous tab",
        "pestaña anterior (⌘⇧[)": "previous tab (⌘⇧[)",
        "pestaña siguiente": "next tab",
        "pestaña siguiente (⌘⇧])": "next tab (⌘⇧])",
        "posición %ld → tecla %ld": "slot %ld → key %ld",
        "preparar un envío remoto y luego pulsar una tecla de agente": "arm a remote send — then press an agent key",
        "rechazar": "reject",
        "rechazar la solicitud pendiente (⎋) / cancelar el modo diversión": "reject pending prompt (⎋) / cancel fun mode",
        "repintar el tablero": "repaint board",
        "requiere Superset": "requires Superset",
        "respiración": "breath",
        "respiración suave": "shallow breath",
        "saltar a un chat": "jumping to a chat",
        "serpiente": "snake",
        "sesión anterior": "previous session",
        "sesión siguiente": "next session",
        "sin asignar": "unassigned",
        "sin conectar": "not wired",
        "sin confirmar": "unconfirmed",
        "sin definir": "not set",
        "sin función": "inert",
        "sin icono": "no icon",
        "sin instalar": "not wired",
        "sin pedir": "not asked",
        "solo modo diversión: macOS lo pide la primera vez que lo reproduces": "fun mode only — macOS asks the first time you play it",
        "tecla %ld": "key %ld",
        "tecla de acción · configurable": "action key · yours to set",
        "tecla de acción · una tapa ancha": "action key · one wide cap",
        "tecla de agente · salta a su posición": "agent key · always jumps to its slot",
        "terminada": "done",
        "texto": "text",
        "texto que enviar": "text to send",
        "tocar para dictar": "tap to dictate",
        "trabajando": "working",
        "tras %ld ms": "after %ldms",
        "traspasar": "hand off",
        "traspasar la terminal activa a otro agente (confirmar con APPR)": "hand the focused terminal off to another agent (confirm with APPR)",
        "¿Permitir que los textos escriban comandos destructivos?": "Let snippets type destructive commands?",
        "¿Qué color hay en cada tecla?": "Which color is on which key?",
        "Ámbar": "Amber",
        "Última comprobación: %@.": "Last checked %@.",
        "⌃Y asignado a voice:pushToTalk. Las sesiones nuevas de Claude Code lo toman; las ya abiertas conservan sus atajos anteriores hasta que las reinicies.": "Bound ⌃Y to voice:pushToTalk. New Claude Code sessions pick it up — ones already open keep their old bindings until restarted.",
        "⌃Y ya está asignado a %@ en tus keybindings: la tecla de voz no hará nada hasta que liberes ese atajo o lo cambies aquí.": "⌃Y is already bound to %@ in your keybindings — the voice key will do nothing until that binding is freed or changed here.",
        "Clásico": "Classic",
        "Gamer": "Gamer",
        "IA": "AI",
        "Pop": "Pop",
        "Claude": "Claude",
        "Los colores de fábrica del pad.": "The pad's own colors.",
        "Neón sobre negro: saturado y con mucho contraste.": "Neon on black: saturated, high contrast.",
        "Azules y violetas fríos; los avisos siguen siendo cálidos.": "Cool blues and violets; prompts stay warm.",
        "Colores vivos de caramelo.": "Bright candy colors.",
        "El terracota, el marfil y los neutros de Anthropic.": "Anthropic's terracotta, ivory and neutrals.",
        "Tema": "Theme",
        "Colores del pad de un golpe: estados, paleta de espacios y confirmación. Cada estado conserva su significado.": "The pad's colors in one go: states, workspace palette and confirmation. Every state keeps its meaning.",
        "Personalizado": "Custom",
        "Tus colores, editados a mano.": "Your colors, edited by hand.",
        "Muestra el tema en las teclas unos segundos, sin aplicarlo.": "Shows the theme on the keys for a few seconds, without applying it.",
        "Tema en uso": "Theme in use",
        "Tema propio": "Your theme",
        "Guardar como tema…": "Save as theme…",
        "Importar": "Import",
        "Desde un archivo…": "From a file…",
        "Pegar del portapapeles": "Paste from the clipboard",
        "¿Borrar el tema «%@»?": "Delete the theme “%@”?",
        "Los colores que lleva ahora el pad no cambian.": "The colors the pad wears now stay as they are.",
        "No se pudo importar el tema": "Could not import the theme",
        "Guardar como tema": "Save as theme",
        "Guarda los colores que lleva ahora el pad: estados, paleta y confirmación.": "Saves the colors the pad wears now: states, palette and confirmation.",
        "Mi tema": "My theme",
        "Importar tema": "Import theme",
        "Se añade a tus temas; no se aplica hasta que elijas su tarjeta.": "It is added to your themes; it is not applied until you choose its card.",
        "Renombrar tema": "Rename theme",
        "Renombrar": "Rename",
        "Tema exportado a %@.": "Theme exported to %@.",
        "No se pudo escribir %@.": "Could not write %@.",
        "JSON de «%@» copiado al portapapeles.": "JSON for “%@” copied to the clipboard.",
        "No se pudo leer %@.": "Could not read %@.",
        "El portapapeles no tiene texto.": "The clipboard has no text.",
        "Incumple reglas de legibilidad": "Breaks readability rules",
        "Duplicar": "Duplicate",
        "Renombrar…": "Rename…",
        "Exportar a archivo…": "Export to a file…",
        "Copiar como JSON": "Copy as JSON",
        "Borrar…": "Delete…",
        "Más acciones": "More actions",
        "Este tema incumple reglas de legibilidad:": "This theme breaks readability rules:",
        "Puedes guardarlo igualmente; su tarjeta llevará ⚠︎.": "You can save it anyway; its card will carry ⚠︎.",
        "Guardar de todas formas": "Save anyway",
        "falta %@": "%@ is missing",
        "%@ tiene más de %@ caracteres": "%@ has more than %@ characters",
        "%@ «%@» no es un efecto válido": "%@ “%@” is not a valid effect",
        "%@ está vacía": "%@ is empty",
        "%@ tiene más de %@ colores": "%@ has more than %@ colors",
        "%@ «%@» no es un color": "%@ “%@” is not a color",
        "%@ debe estar entre 0 y 1": "%@ must be between 0 and 1",
        "No es un tema de OpenBoard: falta «openboardTheme».": "Not an OpenBoard theme: “openboardTheme” is missing.",
        "Tema de la versión %@, y este OpenBoard solo lee la versión 1.": "A version %@ theme; this OpenBoard only reads version 1.",
        "El tema no es válido: %@.": "The theme is not valid: %@.",
        "«%@» es demasiado gris para leerse como un color.": "“%@” is too grey to read as a color.",
        "«%@» debe ser cálido (5–45°); este está en %@°.": "“%@” must be warm (5–45°); this one is at %@°.",
        "«%@» debe ser rojo (330–10°); este está en %@°.": "“%@” must be red (330–10°); this one is at %@°.",
        "«%@» debe ser verde (75–165°); este está en %@°.": "“%@” must be green (75–165°); this one is at %@°.",
        "«%@» debe ser azul o frío (180–275°); este está en %@°.": "“%@” must be blue or cool (180–275°); this one is at %@°.",
        "«%@» y «%@» están a solo %@° y se confunden.": "“%@” and “%@” are only %@° apart and look alike.",
        "la confirmación": "the confirmation",
        "«%@» usa un tono de atención (%@°) y parecería un aviso.": "“%@” uses an attention hue (%@°) and would look like a prompt.",
        "El color de espacio %@ está a %@° de «%@»: el pad lo saltará.": "Workspace color %@ is %@° from “%@”: the pad will skip it.",
        "El color de espacio %@ se parece demasiado a «%@».": "Workspace color %@ looks too much like “%@”.",
        "Los colores de espacio %@ y %@ se distinguen mal.": "Workspace colors %@ and %@ are hard to tell apart.",
        "«%@» debe brillar claramente más que «%@» (al menos 1,5 veces).": "“%@” must be clearly brighter than “%@” (at least 1.5×).",
        "«%@» debe brillar más que «%@».": "“%@” must be brighter than “%@”.",
        "Ponle un nombre.": "Give it a name.",
        "El nombre puede tener como mucho %@ caracteres.": "The name can be at most %@ characters.",
        "Ya hay un tema que se llama «%@».": "There is already a theme called “%@”.",
        "%@ (copia)": "%@ (copy)",
        "Tema propio · avisos: %@": "Your theme · warnings: %@",
        "Probándolo en el pad; se aplica al terminar.": "Playing it on the pad; it applies when that ends.",
    ]
}
